language: node_js

node_js:
  - "7"

script: 
  - npm run bootstrap
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION

cache:
  directories:
  - node_modules
  - packages/sentry-client/node_modules
  - packages/sentry-server-data/node_modules
  - packages/sentry-server-host/node_modules

notifications:
  email: false