language: node_js

node_js:
  - "7"

script: 
  - npm run bootstrap
  - lerna run test
  - codecov

cache:
  directories:
  - node_modules
  - packages/sentry-client/node_modules
  - packages/sentry-server-data/node_modules
  - packages/sentry-server-host/node_modules

notifications:
  email: false